### ISSUE TITLE
Usage on commercial site

### ISSUE THREAD

**Issue by j6k4m8** [ds300/jetzt#141]
I'm webmaster for a university newsletter. I'm excited about integrating jetzt into the article pages but I want to check here first and see if there's any concern / issue / preferences on the matter before I move forward.

@ds300, I think this'd be your call? (PS: Sorry for having left the contributing scene for a few weeks! It's finals season here.)

**Comment by ds300** [comment]
Hi. Sorry I ignored this issue when it was made. Not sure why I did, it would have taken only a moment so say 'Sure, go ahead!'. Probably a mix forgetfulness and being burnt out. Please forgive me. I'll close this issue now.
