### ISSUE TITLE
Safari CSS and key binding errors

### ISSUE THREAD

**Issue by sztojka** [ds300/jetzt#146]
The bookmarklet looks like this in safari:
![jetzt-safari](https://cloud.githubusercontent.com/assets/2893181/6641296/3f8abede-c99d-11e4-8283-dff3faea30bc.png)

Keyword bindings aren't working neither: space, up and down keys. 

I tried to fix the CSS first, but can't figure out why absolute positioning doesn't work, because that is why the UI part breaks down.

**Comment by j6k4m8** [comment]
I don't have Safari so I can't test... But my understanding is that some versions of the browser have very weird bugs with absolute positioning.

**Comment by ds300** [comment]
*shrug*. I don't personally use safari or even jetzt, so won't be investigating this, but you are of course welcome to submit a PR if you figure out the issue.

**Comment by peteruithoven** [comment]
I don't use Safari either, but I can confirm the issue. 
It's not that a percentage is used for `top`?

**Comment by sztojka** [comment]
The problem lies somewhere in the absolute positioning inside a fixed container, since changing .sr-progress -s "bottom: -10px" to "bottom: -80px" puts the progressbar just beneath the box where it should be.

**Comment by sztojka** [comment]
Okay It looks like it was a flexbox issue, I was able to solve it. I send a PR soon.

**Comment by peteruithoven** [comment]
Nice!
