### ISSUE TITLE
Strange dash behavior

### ISSUE THREAD

**Issue by alaska** [ds300/jetzt#149]
When reading [this article](http://www.dukechronicle.com/article/2015/08/just-try-it) I noticed there were dashes splitting words where they didn't appear in the document. "Under-graduate", for example.  Wondering where this comes from, and whether or not something can be done to avoid it.

**Comment by alaska** [comment]
Is this simply related to the width of the word?

**Comment by ds300** [comment]
Yup. Words longer than 13 characters are broken up, as they are deemed to be too long to read accurately at speed.

**Comment by alaska** [comment]
Have you considered using a hyphenization algorithm? Would you accept a patch for it?

**Comment by ds300** [comment]
Sure, that'd be awesome. There was talk about using TeX's algorithm in #117 but nothing ever came of it. It would have to fallback gracefully if the language of the text doesn't fit the model, and if it ends up being a ton of code I probably won't put it in the bookmarklet, but otherwise go ahead. :+1:

**Comment by alaska** [comment]
Was gonna shoehorn this guy in.  Seems fairly compact, and would only work on English initially: https://github.com/cuzzo/Hyphenator

**Comment by ds300** [comment]
sounds good, just couple it with some sensible english detection or make it an off-by-default option and I'll happily merge it in.

**Comment by alaska** [comment]
Is there a repo with the un-minimized code somewhere?

**Comment by ds300** [comment]
yeah the source files are in `/modules`.
