### ISSUE TITLE
Bookmarklet and speed

### ISSUE THREAD

**Issue by sergeevabc** [ds300/jetzt#159]
Imagine Jetzt lives on Firefox’s bookmarks toolbar. Upon activation it sets speed to 400 words per minute. How to change this behavior, e.g. make default speed slower? Perhaps there is (could be) a way to pass speed parameter within code of bookmarklet (so everybody could customize according to his needs)?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by peteruithoven** [comment]
Don't be rude, we're all volunteers. 
Please see issues like: 
- https://github.com/ds300/jetzt/issues/145
- https://github.com/ds300/jetzt/pull/22

**Comment by sergeevabc** [comment]
> #145 
> In jetzt.solid.min.js search for the substring target_wpm:400 and change 400 to whatever WPM you like.
It implies rehosting custom version of script somewhere. Not flexible at all.
Hence the question whether author could alter current script to pass this parameter via bookmarklet.

**Comment by ds300** [comment]
Hey @sergeevabc , sorry I don't actively work on this project any more, but would be happy to review a PR if you have the time.

**Comment by sergeevabc** [comment]
Had user been able to polish reported roughness, he would be called a developer.
The latter role is yours, hence the badge, yet passion to carry on seems to be lost.
Consider marking project as abandoned to strangle illusory hopes for changes at birth.

**Comment by ds300** [comment]
It is often unrealistic to expect the maintainers of an open source project
to implement one's feature requests. It is always uncouth to become pissy
when they do not.

I will not mark the project as abandoned. If bugs are reported I will
attempt to fix them. But I am not currently inclined to implement new
features for a thing I don't even use. Unless somebody is willing to pay.

You still want a customisable bookmarklet? My rate is 600€ a day.

**Comment by sergeevabc** [comment]
Core value of open source philosophy besides freedom to look inside is to make life easier voluntarily.
And making life easier means doing, even with loose schedules and vague roles, not procrastination.
Whereas you, @ds300, have been neglecting the community _for years_ with no courage to be honest.
Instead you feed us with unfeasible promises and extort money, thus disgracing your name.

**Comment by gywn** [comment]
The core value of open source philosophy besides freedom is to **share** solutions that make **one's** life easier.

By releasing his software under the Apache License, @ds300 has granted everyone possibility to modify and use freely his code at **one's** intention. That's something huge.

Similarly, all the other things, like whether the creator will merge or update or not, is up to **his** intention as well.

**Comment by sergeevabc** [comment]
@gywn, we’re at the public issue tracker and not within his private walls, hence the public expectations.
Would you like to share with no further responsibility? Have a courage to state this in the first place.

**Comment by gywn** [comment]
@sergeevabc That's exactly what the 8th term (Limitation of Liability) in the Apache License is for.

**Comment by sergeevabc** [comment]
@gywn, software license might help you to talk a way out of trouble within the walls of court, outside there is always another [Vitaly Kaloyev][1] waiting to counterbalance unfair selfish recreant behaviour.
You gain people’s trust, they rely on you, and then gone fishing without notice? Unfair, selfish, recreant.   

[1]: https://en.wikipedia.org/wiki/Vitaly_Kaloyev

**Comment by peteruithoven** [comment]
I feel like @sergeevabc is trolling us

**Comment by ds300** [comment]
Did he just imply that I deserve to be murdered? For releasing some free software and then not wanting to work on it anymore? Daaamn. Brother has high standards.

**Comment by gywn** [comment]
@sergeevabc You failed to the creator's selflessness in the first place, and turn moralism into threats of legal illiteracy. We might just end the conversations here.

**Comment by sergeevabc** [comment]
> Did he just imply that I deserve to be murdered?

@ds300, it means you deserve all this public censure since you offended the community (or betrayed the brotherhood, if you will) by committing the sin of sloth [for years][1] (i.e. laziness, carelessness, unwillingness to act, half-hearted effort). 

> …not wanting to work on it anymore…

Have the guts to [inform the public][2] a new maintainer is wanted so no improvement should be expected until then and go through opened issues and repent for unfulfilled promises and ignored calls.

[1]: https://github.com/ds300/jetzt/issues
[2]: https://github.com/ds300/jetzt/blob/master/README.md

**Comment by peteruithoven** [comment]
ds300 took the time just a few months ago to merge a couple of pull requests: https://github.com/ds300/jetzt/pulls

Referencing [Vitaly Kaloyev ](https://en.wikipedia.org/wiki/Vitaly_Kaloyev) is really uncalled for. @sergeevabc I've reported you with Github.

**Comment by sergeevabc** [comment]
@peteruithoven, merging pull requests is interaction between developers, while dozens of issues posted by ordinary people are neglected [for years][1], some of them stays without even a basic reply out of decency. And don’t forget to send screenshots to police to make them laugh about referencing Wikipedia.

[1]: https://github.com/ds300/jetzt/issues
